name: total_double
description: Total Double

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  
  sizer: ^2.0.15
  flutter_localizations:
    sdk: flutter
  intl: any
 
  pwa_install: ^0.0.5



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
    - assets/
    - assets/icon/
  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Medium.ttf
          style: normal
   
      
